version: 2
updates:
  - directory: /
    package-ecosystem: docker
    rebase-strategy: auto
    schedule:
      interval: weekly
  - directory: /
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      interval: weekly
