name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Docker build and run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker buildx create --use --driver=docker-container
    - uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: false
        tags: karnauskas/action-imaptest:latest
