name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Docker build and run
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - run: docker buildx create --use --driver=docker-container
    - uses: docker/build-push-action@32945a339266b759abcbdc89316275140b0fc960 # v6.8.0
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: false
        tags: karnauskas/action-imaptest:latest
